name: Detect Upstream Changes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  check-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/raysunplus/opencti.git
          git fetch upstream

      - name: Compare upstream with fork
        id: compare
        run: |
          UPSTREAM=$(git rev-parse upstream/main)
          FORK=$(git rev-parse origin/main)
          echo "upstream=$UPSTREAM" >> $GITHUB_OUTPUT
          echo "fork=$FORK" >> $GITHUB_OUTPUT

      - name: Trigger webhook if changes exist
        if: steps.compare.outputs.upstream != steps.compare.outputs.fork
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"upstream":"'${{ steps.compare.outputs.upstream }}'"}' \
            http://185.204.170.162:15000/webhook